interface ZEMPLOYEES
  public .


  types:
    BEGIN OF STR,
    MANDT TYPE ZEMPLOYEE-mandt,
    EMP_ID TYPE ZEMPLOYEE-emp_id,
    FIRST_NAME TYPE ZEMPLOYEE-FIRST_NAME,
    LAST_NAME TYPE ZEMPLOYEE-LAST_NAME,
    FULL_NAME TYPE ZEMPLOYEE-FULL_NAME,
    GENDER TYPE ZEMPLOYEE-GENDER,
    DOB TYPE ZEMPLOYEE-DOB,
    POSITIONS TYPE ZEMPLOYEE-POSITIONS,
    JOIN_DATE TYPE ZEMPLOYEE-JOIN_DATE,
    SALARY TYPE ZEMPLOYEE-SALARY,
    NATIONAL_ID TYPE ZEMPLOYEE-NATIONAL_ID,
    EMAIL TYPE ZEMPLOYEE-EMAIL,
    PHONE TYPE ZEMPLOYEE-PHONE,
    ADDRESS TYPE ZEMPLOYEE-ADDRESS,
    MARITAL_STATUS TYPE ZEMPLOYEE-MARITAL_STATUS,
    STATUS TYPE ZEMPLOYEE-STATUS,
    CREATED_BY TYPE ZEMPLOYEE-CREATED_BY,
    CREATED_ON TYPE ZEMPLOYEE-CREATED_ON,
    CHANGED_BY TYPE ZEMPLOYEE-CHANGED_BY,
    CHANGED_ON TYPE ZEMPLOYEE-CHANGED_ON,
    END OF STR .

  data:
    IT_DATA TYPE TABLE OF STR .
  data IS_DATA type STR .

  methods RETURN_MAIN_SCREEN .
endinterface.